### ISSUE TITLE
It just redirects to ned.im

### ISSUE THREAD

**Issue by AstroLive8333** [needim/needim.github.io#2]
I’m curious, how do you make it redirect to a website as soon as it opens? I wanna know how to make it redirect like that (if there is one file that does it just tell me which one)

**Comment by needim** [comment]
I'm not if I understand correctly but you can check this doc.

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by AstroLive8333** [comment]
Oh, it’s not JavaScript just sending you to a website? I know about the GitHub custom domains, but I thought that you had just redirected it via JavaScript. Thank you, I will check that doc out.
